# Generated by Django 3.2.2 on 2021-07-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
